package com.capg.entity;

import com.capg.dto.FlightsDTO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "flights")  // Specify the table name (optional)
public class Flights {

    public static final String SEQUENCE_NAME = null;

	// The flightId will now be auto-generated by MySQL (auto-increment)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Auto-increment in MySQL
    private int flightId;
    
    private String flightName;
    private String origin;
    private String destination;
    private String departureTime;
    private String arrivalTime;
    private Integer seats;
    private Integer fare;

    // Constructor to map FlightsDTO to Flights entity
    public Flights(FlightsDTO flightsDTO) {
        this.flightId = flightsDTO.getFlightId();
        this.flightName = flightsDTO.getFlightName();
        this.origin = flightsDTO.getOrigin();
        this.destination = flightsDTO.getDestination();
        this.departureTime = flightsDTO.getDepartureTime();
        this.arrivalTime = flightsDTO.getArrivalTime();
        this.seats = flightsDTO.getSeats();
        this.fare = flightsDTO.getFare();
    }
}
